### ISSUE TITLE
Project scope/naming

### ISSUE THREAD

**Issue by aloiscochard** [rahulmutt/ghcvm#1]
Hi Rahul,

I was wondering about the naming and the scope you want to cover here, the reason I ask is because with a name with `ghcvm` I would expect it to potentially try to target different vm, or to implement a vm itself.

Wouldn't be `ghcjvm` more appropriate? (it also reflect the naming used by the JS backend)

Cheers!

**Comment by rahulmutt** [comment]
Hi Alois,

The choice of the more generic suffix "VM" vs "JVM" was intentional. MSIL (intermediate languages that run on CLR, for langauges like C#, VisualBasic, etc.) and JVM bytecode are similar enough where I can foresee the code generator, once stable for the JVM, could in a month's work be transferred to be compatible with CLR. To be honest, I have almost zero knowledge of the CLR besides writing a small Kinect application for a friend a couple years ago, but I do know it borrowed a lot of ideas (and bytecodes) from the JVM.

The long term goal of this project is to be compatible with the existing infrastructure of large enterprises, which is currently dominated (fortunately or unfortunately) by the JVM and CLR. So you can bet that underlying all the major design decisions I make will involve that goal one way or another. Since I have more experience with the JVM and due to the popularity of the Android platform (which uses a JVM-derivative, Dalvik), I decided to start with the JVM and worry about the other major platform later.

Hope that helps!

**Comment by aloiscochard** [comment]
That makes perfect sense!

I had similar hope for Kuna, as I agree, fundamentally most transformation done for the JVM should be reusable for the CLR.

Great stuff
