### ISSUE TITLE
Weird behaviour in presence of `fromEnum`, `!!`

### ISSUE THREAD

**Issue by psibi** [rahulmutt/ghcvm#104]
Package name: old-time

Install it from here: https://github.com/psibi/old-time-eta

I'm facing a weird issue - Basically with the combination of `fromEnum`, `!!` - it's picking up the next element in the list. I have not been able to produce a minimal reproducible example for the issue, but I can reproduce it deterministically in the ported working library I'm currently working on. I don't know if I'm missing something basic here or if it's a bug in the compiler.

A test code which represents the bug:

``` haskell
module Main where

import System.Time

main :: IO ()
main = do
    let x = TOD 1477242123 372000000000 :: ClockTime
    print $ show x
```

On executing it, this produces:

``` shellsession
@sibi::jane { ~/scripts }-> java -classpath Out.jar ghcvm.main
CalendarTime {ctYear = 2016, ctMonth = October, ctDay = 23, ctHour = 22, ctMin = 32, ctSec = 3, ctPicosec = 0, ctWDay = Sunday, ctYDay = 297, ctTZName = "India Standard Time", ctTZ = 19800, ctIsDST = False}
"Sun Nov 23 22:32:03 India Standard Time 2016"
```

Even though `ctMonth = October`, it prints `Nov` in the second
line. If you trace the execution, it doesn't make sense. I have
modified the `show` instance for `ClockTime` to demonstrate this
behaviour. You can see the show instance from `System.Time` module to
follow the workflow.

Any idea why this is happening ? This has killed around 4 hours of my day :(

**Comment by rahulmutt** [comment]
It turns out this was an off-by-one error. There's a primitive operation that converts a data constructor to a tag and that tag was one off what it should be. Fixed on master. Make sure you do a cleaninstall. We probably would've encountered this sooner if we had tests going. Let's try to get that setup this week.

Since we're in testing phase and the code we're porting is known to work in Haskell, you can more often than not assume it's a compiler bug if the desired behaviour isn't achieved. Feel free to report sooner as opposed to later - the worst thing that can happen is that it's a trivial Haskell fix which isn't a big deal.
