### ISSUE TITLE
Add travis CI integration

### ISSUE THREAD

**Issue by psibi** [rahulmutt/ghcvm#63]
For the initial start, the test can be just a simple hello world and the prime number example which is documented in the wiki.

**Comment by psibi** [comment]
Is this useful right now ?

**Comment by rahulmutt** [comment]
Yeah it will be. I was planning on it once we have port some simple tests/benchmarks over from GHC, but we can do it now. There's a 'test/verify/verify.sh' script that tests for bytecode errors in the libraries that are bundled with GHCVM, so that can be a start. It requires `javac` and a full GHCVM installation.

**Comment by rahulmutt** [comment]
Done as of #64
