### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by prt2121** [rahulmutt/ghcvm#7]
Hi there,
Thanks for this cool project. I tried to build it on my mac but I got some errors: looks like some dependencies are missing

```
>./build.sh                                                
mtl-2.2.1: using precompiled package
data-default-0.5.3: configure
monadloc-0.7.1: download
binary-state-0.1.1: download
data-default-0.5.3: build
bindings-libzip-0.10.2: configure
data-default-0.5.3: copy/register
monadloc-0.7.1: configure
monadloc-0.7.1: build
binary-state-0.1.1: configure
binary-state-0.1.1: build
monadloc-0.7.1: copy/register
binary-state-0.1.1: copy/register
Progress: 5/23
--  While building package bindings-libzip-0.10.2 using:
      /Users/prat/.stack/setup-exe-cache/x86_64-osx/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.5.0 configure --with-ghc=/usr/local/bin/ghc --with-ghc-pkg=/usr/local/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/pkgdb --libdir=/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/lib --bindir=/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/bin --datadir=/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/share --libexecdir=/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/libexec --sysconfdir=/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/etc --docdir=/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/doc/bindings-libzip-0.10.2 --htmldir=/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/doc/bindings-libzip-0.10.2 --haddockdir=/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/doc/bindings-libzip-0.10.2 --dependency=base=base-4.8.2.0-bfcc6de9ee2962ae54db40ece3022dc5 --dependency=bindings-DSL=bindings-DSL-1.0.23-75369fdfdd50bafd3a7650315e217654
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/prat/prt/ghcvm/.stack-work/logs/bindings-libzip-0.10.2.log

    Configuring bindings-libzip-0.10.2...
    setup-Simple-Cabal-1.22.5.0-ghc-7.10.3: The pkg-config package 'libzip'
    version ==0.10.* is required but it could not be found.
Executable named rtsbuild not found on path: ["/Users/prat/prt/ghcvm/.stack-work/install/x86_64-osx/lts-5.11/7.10.3/bin","/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/bin","/Users/prat/.stack/programs/x86_64-osx/ghc-7.10.2/bin/ghc","/Users/prat/.local/bin","/Users/prat/.cabal/bin","/usr/local/bin","/usr/local/sbin","/usr/bin","/bin","/usr/sbin","/sbin","/usr/local/git/bin","/usr/local/munki","/Users/prat/Library/Android/sdk/tools","/Users/prat/Library/Android/sdk/platform-tools","/Users/prat/.cargo/bin","/Users/prat/.cabal/bin"]
Executable named rtsbuild not found on path: ["/Users/prat/prt/ghcvm/.stack-work/install/x86_64-osx/lts-5.11/7.10.3/bin","/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/bin","/Users/prat/.stack/programs/x86_64-osx/ghc-7.10.2/bin/ghc","/Users/prat/.local/bin","/Users/prat/.cabal/bin","/usr/local/bin","/usr/local/sbin","/usr/bin","/bin","/usr/sbin","/sbin","/usr/local/git/bin","/usr/local/munki","/Users/prat/Library/Android/sdk/tools","/Users/prat/Library/Android/sdk/platform-tools","/Users/prat/.cargo/bin","/Users/prat/.cabal/bin"]
```

Any suggestion? Thanks again!

**Comment by rahulmutt** [comment]
Looks like you don't have libzip (a C dependency) installed. Maybe you have to install it with brew?I actually meant to highlight the libzip dependency in the README, but I forgot about it. Will update when I get access to my laptop. PR for updating the README is welcome.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: PratSent: Thursday 19 May 2016 8:04 PMTo: rahulmutt/ghcvmReply To: rahulmutt/ghcvmSubject: [rahulmutt/ghcvm] Build Failure (#7)Hi there,
Thanks for this cool project. I tried to build it on my mac but I got some errors: looks like i missed some dependencies.

>./build.sh                                                
mtl-2.2.1: using precompiled package
data-default-0.5.3: configure
monadloc-0.7.1: download
binary-state-0.1.1: download
data-default-0.5.3: build
bindings-libzip-0.10.2: configure
data-default-0.5.3: copy/register
monadloc-0.7.1: configure
monadloc-0.7.1: build
binary-state-0.1.1: configure
binary-state-0.1.1: build
monadloc-0.7.1: copy/register
binary-state-0.1.1: copy/register
Progress: 5/23
--  While building package bindings-libzip-0.10.2 using:
      /Users/prat/.stack/setup-exe-cache/x86_64-osx/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.5.0 configure --with-ghc=/usr/local/bin/ghc --with-ghc-pkg=/usr/local/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/pkgdb --libdir=/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/lib --bindir=/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/bin --datadir=/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/share --libexecdir=/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/libexec --sysconfdir=/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/etc --docdir=/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/doc/bindings-libzip-0.10.2 --htmldir=/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/doc/bindings-libzip-0.10.2 --haddockdir=/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/doc/bindings-libzip-0.10.2 --dependency=
 base=base-4.8.2.0-bfcc6de9ee2962ae54db40ece3022dc5 --dependency=bindings-DSL=bindings-DSL-1.0.23-75369fdfdd50bafd3a7650315e217654
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/prat/prt/ghcvm/.stack-work/logs/bindings-libzip-0.10.2.log

    Configuring bindings-libzip-0.10.2...
    setup-Simple-Cabal-1.22.5.0-ghc-7.10.3: The pkg-config package 'libzip'
    version ==0.10.* is required but it could not be found.
Executable named rtsbuild not found on path: ["/Users/prat/prt/ghcvm/.stack-work/install/x86_64-osx/lts-5.11/7.10.3/bin","/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/bin","/Users/prat/.stack/programs/x86_64-osx/ghc-7.10.2/bin/ghc","/Users/prat/.local/bin","/Users/prat/.cabal/bin","/usr/local/bin","/usr/local/sbin","/usr/bin","/bin","/usr/sbin","/sbin","/usr/local/git/bin","/usr/local/munki","/Users/prat/Library/Android/sdk/tools","/Users/prat/Library/Android/sdk/platform-tools","/Users/prat/.cargo/bin","/Users/prat/.cabal/bin"]
Executable named rtsbuild not found on path: ["/Users/prat/prt/ghcvm/.stack-work/install/x86_64-osx/lts-5.11/7.10.3/bin","/Users/prat/.stack/snapshots/x86_64-osx/lts-5.11/7.10.3/bin","/Users/prat/.stack/programs/x86_64-osx/ghc-7.10.2/bin/ghc","/Users/prat/.local/bin","/Users/prat/.cabal/bin","/usr/local/bin","/usr/local/sbin","/usr/bin","/bin","/usr/sbin","/sbin","/usr/local/git/bin","/usr/local/munki","/Users/prat/Library/Android/sdk/tools","/Users/prat/Library/Android/sdk/platform-tools","/Users/prat/.cargo/bin","/Users/prat/.cabal/bin"]


Any suggestion. Thanks again!

—You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub

**Comment by prt2121** [comment]
sorry for bothering again, after fixing the libzip issue, i got new errors.

```
> ./build.sh
Cleaning files in rts/build
Build completed in 0:01m
# cpp (for rts/build/ghcvm/runtime/types/Task.java)
clang: error: no input files
# cpp (for rts/build/ghcvm/runtime/types/StgTSO.java)
clang: error: no input files
# cpp (for rts/build/ghcvm/runtime/types/SparkPool.java)
clang: error: no input files
# cpp (for rts/build/ghcvm/runtime/types/SparkCounters.java)
...
... removed for brevity
...
# cpp (for rts/build/ghcvm/runtime/RtsMain.java)
clang: error: no input files
# cpp (for rts/build/ghcvm/runtime/Rts.java)
clang: error: no input files
# javac (for rts/build/rts.jar)
# jar (for rts/build/rts.jar)
'c' flag requires manifest or input files to be specified!
Usage: jar {ctxui}[vfmn0PMe] [jar-file] [manifest-file] [entry-point] [-C dir] files ...
If any file is a directory then it is processed recursively.
The manifest file name, the archive file name and the entry point name are
specified in the same order as the 'm', 'f' and 'e' flags.
...
Error when running Shake build system:
* rts/build/rts.jar
user error (Development.Shake.cmd, system command failed
Command: jar cf rts/build/rts.jar
Exit code: 1
Stderr:
'c' flag requires manifest or input files to be specified!
Usage: jar {ctxui}[vfmn0PMe] [jar-file] [manifest-file] [entry-point] [-C dir] files ...

If any file is a directory then it is processed recursively.
The manifest file name, the archive file name and the entry point name are
specified in the same order as the 'm', 'f' and 'e' flags.
...
```
any idea?

**Comment by rahulmutt** [comment]
Yeah, that has to do with the C preprocessor step. 

`cpp -iquote [ghcvm-home]/rts/include [java-file-to-compile]`

That step works on Linux but appears to fail on Mac. Basically, that command removes all the pre-processor directives from the Java file, using the given include path. I'll update `shake/Build.hs` to accommodate Mac builds if you can provide me with a command that does the equivalent task.

**Comment by ExcaliburZero** [comment]
I attempted to build the project in Fedora Linux by running `./build.sh`, and had the same issue with libzip.

```
chris@adrasteia:~/Code/ghcvm (master)$ ./build.sh 
old-time-1.1.0.3: using precompiled package
bindings-libzip-0.10.2: configure
random-1.1: using precompiled package
data-default-0.5.3: download
data-default-0.5.3: configure
hslogger-1.2.9: download
regex-base-0.93.2: download
data-default-0.5.3: build
regex-base-0.93.2: configure
data-default-0.5.3: copy/register
regex-base-0.93.2: build
hslogger-1.2.9: configure
hslogger-1.2.9: build
regex-base-0.93.2: copy/register
hslogger-1.2.9: copy/register
Progress: 6/26
--  While building package bindings-libzip-0.10.2 using:
      /home/chris/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.5.0 configure --with-ghc=/home/chris/.stack/programs/x86_64-linux/ghc-7.10.3/bin/ghc --with-ghc-pkg=/home/chris/.stack/programs/x86_64-linux/ghc-7.10.3/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/home/chris/.stack/snapshots/x86_64-linux/lts-5.11/7.10.3/pkgdb --libdir=/home/chris/.stack/snapshots/x86_64-linux/lts-5.11/7.10.3/lib --bindir=/home/chris/.stack/snapshots/x86_64-linux/lts-5.11/7.10.3/bin --datadir=/home/chris/.stack/snapshots/x86_64-linux/lts-5.11/7.10.3/share --libexecdir=/home/chris/.stack/snapshots/x86_64-linux/lts-5.11/7.10.3/libexec --sysconfdir=/home/chris/.stack/snapshots/x86_64-linux/lts-5.11/7.10.3/etc --docdir=/home/chris/.stack/snapshots/x86_64-linux/lts-5.11/7.10.3/doc/bindings-libzip-0.10.2 --htmldir=/home/chris/.stack/snapshots/x86_64-linux/lts-5.11/7.10.3/doc/bindings-libzip-0.10.2 --haddockdir=/home/chris/.stack/snapshots/x86_64-linux/lts-5.11/7.10.3/doc/bindings-libzip-0.10.2 --dependency=base=base-4.8.2.0-0d6d1084fbc041e1cded9228e80e264d --dependency=bindings-DSL=bindings-DSL-1.0.23-75369fdfdd50bafd3a7650315e217654
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/chris/Code/ghcvm/.stack-work/logs/bindings-libzip-0.10.2.log

    Configuring bindings-libzip-0.10.2...
    setup-Simple-Cabal-1.22.5.0-ghc-7.10.3: The pkg-config package 'libzip'
    version ==0.10.* is required but it could not be found.
Executable named rtsbuild not found on path: ["/home/chris/Code/ghcvm/.stack-work/install/x86_64-linux/lts-5.11/7.10.3/bin","/home/chris/.stack/snapshots/x86_64-linux/lts-5.11/7.10.3/bin","/home/chris/.stack/programs/x86_64-linux/ghc-7.10.3/bin","/usr/lib64/qt-3.3/bin","/usr/local/bin","/usr/local/sbin","/usr/bin","/usr/sbin","/home/chris/.cabal/bin","/home/chris/Muse","/home/chris/.local/bin","/home/chris/bin","/home/chris/Muse","/home/chris/Muse"]
Executable named rtsbuild not found on path: ["/home/chris/Code/ghcvm/.stack-work/install/x86_64-linux/lts-5.11/7.10.3/bin","/home/chris/.stack/snapshots/x86_64-linux/lts-5.11/7.10.3/bin","/home/chris/.stack/programs/x86_64-linux/ghc-7.10.3/bin","/usr/lib64/qt-3.3/bin","/usr/local/bin","/usr/local/sbin","/usr/bin","/usr/sbin","/home/chris/.cabal/bin","/home/chris/Muse","/home/chris/.local/bin","/home/chris/bin","/home/chris/Muse","/home/chris/Muse"]
```

I tried installing the `libzip` and `libzip-devel` Fedora packages, but neither of them met the version required for the build.

```
    Configuring bindings-libzip-0.10.2...
    setup-Simple-Cabal-1.22.5.0-ghc-7.10.3: The pkg-config package 'libzip'
    version ==0.10.* is required but the version installed on the system is
    version 1.1
```

I ran the commands to install libzip 0.10.1 that @prt2121 included in his pull request #8. Then I tried to build the project, but still got the same error with libzip. I tried uninstalling the libzip packages that I installed in case that they were being used over libzip 0.10.1, however that did not resolve the issue either.

**Comment by rahulmutt** [comment]
Hmm this problem with libzip seems like it's going to make ghcvm difficult to build. Right now, `hs-java`, the library we use for byte-code generation depends on `libzip` and @aloiscochard is working to replace `hs-java` with his `codec-jvm`, so these build issues will disappear once that finishes up (in a couple weeks). `codec-jvm` only generates class files and does not have a way of creating JAR files, so that part can be done using a pure Haskell library like [zip](https://github.com/mrkkrp/zip).

**Comment by rahulmutt** [comment]
#10 and #11 should fix the difficulty of the build and I'll make sure to add `Use pure Haskell solutions when possible` to the GHCVM Development Guidelines (to be written in the near future) to keep the build cross-platform.

**Comment by rahulmutt** [comment]
@prt2121 I have removed the dependency on cpp in the build. Can you try building the most recent commit on master? The dependency on libzip will be removed within the next week as I start the work on the code generator.

**Comment by prt2121** [comment]
@rahulmutt looks like it runs without any error now! good job! thanks...i'm closing this now.
